services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=0afabc0997631db48ea1026dd0e0fbba6d99806a5d55518cf7a414b64b49e9103b0ad5119d68976dc69dc6141a8d597897017982a1707fb5cd2d21b5acf3feb6
      - MONGODB_URI=mongodb://mongodb:27017/cafeterie
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb

volumes:
  mongodb_data: